name: PASTORE Bot Chiesa Automatico

on:
  schedule:
    # 1. TUTTI I GIORNI alle 08:00 Italiane (circa 07:00 UTC)
    - cron: '0 7 * * *'
    
    # 2. SOLO SABATO alle 11:00 Italiane (circa 10:00 UTC)
    - cron: '0 10 * * 6'
    
    # 3. SOLO DOMENICA alle 17:00 Italiane (circa 16:00 UTC)
    - cron: '0 16 * * 0'
  
  # Permette di avviarlo a mano se serve (pulsante "Run workflow")
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests pandas matplotlib pillow

    - name: Run Bot Script
      env:
        FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
